### ISSUE TITLE
Where the win rate is recorded in the result log for SMAC experiment?

### ISSUE THREAD

**Issue by ByunghyunYoo** [opendilab/ACE#2]
I ran your code and couldn't find where the win rate in SMAC are recorded.

**Comment by yifan123** [comment]
Thank you for your interest in our work. The win rate can be seen in `seed0/log/evaluator/evaluator_logger.txt`. Additionally, you can use Tensorboard to view the events file located in `seed0/serial/ directory`. Let us know if you have any further questions.

**Comment by ByunghyunYoo** [comment]
In this figure, does "final reward" mean the result (win or lose) of test episode?
Do I have to compute the win rate among these 32 test episodes if I want get the win rate ?

![image](https://user-images.githubusercontent.com/48498869/207997581-46f3cc1d-f672-4198-8274-36ab58cc7bc1.png)

**Comment by yifan123** [comment]
In this figure, "reward_mean" means the result (win or lose) of 32 test episodes.

**Comment by ByunghyunYoo** [comment]
Thank you for your answer.

**Comment by ByunghyunYoo** [comment]
For checking performance in 32 test episodes, I'd like to draw the graph of "reward_mean" over total envstep_count as your paper. But, in "seed0/log/evaluator/evaluator_logger.txt", there is only "train_iter". I think this is different from "total envstep". Where can I find "total envstep" for drawing "total envstep vs. win rate"?

**Comment by yifan123** [comment]
You can use Tensorboard to view the events file located in `seed0/serial/` directory or use scripts just like [this](https://stackoverflow.com/questions/42355122/can-i-export-a-tensorflow-summary-to-csv) to convert a tb file to a csv file.

**Comment by ByunghyunYoo** [comment]
Thank you for your answer.
