### ISSUE TITLE
How to use ACE algorithm in my own environment?

### ISSUE THREAD

**Issue by HailySo** [opendilab/ACE#3]
Maybe it's not appropriate to aks such question here. So if there is any bother, I'll apologize to you and won't put such issue any more.

I have read your paper, it's really elaborate. I think the way to embed the SE-state which contains actions, interactions and states is most suitable algorithm for my cooperative environment just like SMAC. But as a beginner in reinforcement learning, I feel it's so difficult for me to completely understand the whole project including hundred of files. I have read it for 2 days with just some frustration left. 😭 

Could you give me a little tuition about which files should be emphatically read? And is the project not that suitable for directly using in other environment, or maybe self-implement is more suitable?

**Comment by yifan123** [comment]
I apologize for replying to your question so late. 

ACE is implemented based on DI-engine, and you can read some DI-engine (https://github.com/opendilab/DI-engine) documentation to learn how to use it. 

The three most important files in the entire repository are: 

- model: https://github.com/opendilab/ACE/blob/main/ding/model/template/smac_ace.py which includes how to embed the SE-state.

- policy: https://github.com/opendilab/ACE/blob/main/ding/policy/ace_dqn.py The `forward_learn` function includes the logic for learning, `forward_collect` contains the logic for collecting data, and `forward_eval` contains the logic for testing.

Thank you very much for your interest in our work. If you have any questions, please feel free to continue this conversation. I have set issue reminders to strong reminders.

**Comment by GuoPingPan** [comment]
If there is any config.py you can provide?

**Comment by yifan123** [comment]
> If there is any config.py you can provide?

In which environment do you wish to deploy ACE algorithms: SMAC, GRF, or other environments?

**Comment by GuoPingPan** [comment]
GRF
